from django import forms

class ContactForm(forms.Form):
    mrz_type = forms.CharField(required=False)
    valid_score = forms.CharField(required=False)
    date_of_birth = forms.CharField(required=True)
    type = forms.CharField(required=False)
    number = forms.CharField(required=True)
    date_of_birth = forms.CharField(required=True)
    expiration_date = forms.CharField(required=False)
    nationality = forms.CharField(required=True)
    sex = forms.CharField(required=True)
    names = forms.CharField(required=True)
    surname = forms.CharField(required=True)
    personal_number = forms.CharField(required=False)
    check_number = forms.CharField(required=False)
    check_date_of_birth = forms.CharField(required=False)
    check_expiration_date = forms.CharField(required=False)
    check_composite = forms.CharField(required=False)
    check_personal_number = forms.CharField(required=False)
    valid_number = forms.BooleanField(required=False)
    valid_date_of_birth = forms.BooleanField(required=False)
    valid_expiration_date = forms.BooleanField(required=False)
    valid_composite = forms.BooleanField(required=False)
    valid_personal_number = forms.BooleanField(required=False)
    method = forms.CharField(required=False)
    walltime = forms.CharField(required=False)
    filename = forms.CharField(required=True)
